Code refactoring to share common options.

diff --git a/scbi-lint b/scbi-lint
--- a/scbi-lint
+++ b/scbi-lint
@@ -1,12 +1,8 @@
 #!/bin/bash
 
-SCBI_VERSION=@VERSION@
-
-DO_HELP=no
 DO_WARNING=yes
 
-SCBI_PLUGINS_LIST=""
-SCBI_PLUGINS="$PWD/scripts.d"
+SCBI_PLUGINS_LIST=()
 
 function usage()
 {
@@ -19,10 +15,15 @@ function usage()
     echo "   -h | --help             this help message"
     echo "   -v | --version          display driver & plug-ins versions"
     echo "      | --plugins=<dir>    specify the plugins' directory"
-    echo "   -e | --error            report only errors"
+    echo "      | --error            report only errors"
 }
 
-[[ $1 == "subcommand" ]] && shift
+if [[ $1 == "subcommand" ]]; then
+    shift
+else
+    echo "error: use scbi lint [options]"
+    exit 1
+fi
 
 ALLOPTS=$(getopt -u -o ehv -l error,help,version,plugins: -- $*)
 
@@ -30,28 +31,13 @@ set -- $ALLOPTS
 
 while [[ $# -gt 0 ]]; do
     case $1 in
-        -h|--help)
-            DO_HELP=yes
-            break
-            ;;
-        -v|--version)
-            DO_VERSION=yes
-            break
-            ;;
-        -e|--error)
+        --error)
             DO_WARNING=no
-            ;;
-        --plugins)
-            SCBI_PLUGINS=$2; shift
-            if [[ ! -d "$SCBI_PLUGINS" ]]; then
-                echo "$0: plugins directory not found"
-                exit 1
-            fi
             ;;
         (--)
             ;;
         (*)
-            SCBI_PLUGINS_LIST+=" $1"
+            SCBI_PLUGINS_LIST+=( $1 )
             ;;
         (-*)
             echo "$0: error - unrecognized option $1" 1>&2; exit 1
@@ -408,7 +394,7 @@ function cygpath()
     true
 }
 
-for PLUGIN in $SCBI_PLUGINS_LIST; do
+for PLUGIN in ${SCBI_PLUGINS_LIST[*]}; do
     PLG=$PLUGIN
     [[ ! -f $PLG ]] && PLG=$SCBI_PLUGINS/$PLG
     if [[ ! -f $PLG ]]; then
diff --git a/scbi-store b/scbi-store
--- a/scbi-store
+++ b/scbi-store
@@ -1,16 +1,8 @@
 #!/bin/bash
 
-SCBI_VERSION=@VERSION@S
-SCBI_PLUGINS="$PWD/scripts.d"
-DO_VERSION=no
-DO_HELP=no
 DO_LIST=no
 DO_DELETE=no
-DO_STAT=no
-DO_PLAN=no
-SCBI_MODULES=no
-ENV_NAME=${SCBI_DEFAULT_ENV:+-$SCBI_DEFAULT_ENV}
-KEY=""
+SCBI_STORE_KEYS=()
 
 ############################################## sto-usage
 #
@@ -138,13 +130,15 @@ function sto-record()
 
 if [[ $1 == "subcommand" ]]; then
     shift
+else
+    echo "error: use scbi store [options]"
+    exit 1
 fi
 
 OPTFILE=$(mktemp)
-OPTARG=
 
-ALLOPTS=$(getopt -u -o kehvld \
-             -l env,plugins:,version,help,list-keys,list:full:,list,delete \
+ALLOPTS=$(getopt -u -o kld \
+             -l list-keys,list:full:,list,delete \
              -- $* 2> $OPTFILE)
 
 if [[ $? != 0 ]]; then
@@ -158,18 +152,6 @@ set -- $ALLOPTS
 
 while [[ $# -gt 0 ]]; do
     case $1 in
-        -h|--help)
-            DO_HELP=yes
-            break
-            ;;
-        -v|--version)
-            DO_VERSION=yes
-            break
-            ;;
-        -e|--env)
-            ENV_NAME="$2"
-            shift
-            ;;
         -k|--list-keys)
             DO_LIST=yes
             ;;
@@ -181,15 +163,6 @@ while [[ $# -gt 0 ]]; do
             ;;
         -d|--delete)
             DO_DELETE=yes
-            ;;
-        --plugins)
-            SCBI_PLUGINS=$2; shift
-            if [[ ! -d "$SCBI_PLUGINS" ]] || \
-                   [[ -z "$(ls $SCBI_PLUGINS/[0-9]* 2> /dev/null)" ]];
-            then
-                echo "$0: no plugins found in $SCBI_PLUGINS"
-                exit 1
-            fi
             ;;
         (--)
             ;;
@@ -204,12 +177,10 @@ while [[ $# -gt 0 ]]; do
     shift
 done
 
-if [[ $DO_HELP = yes ]]; then
+if [[ $DO_HELP == yes ]]; then
     sto-usage
     exit 0
 fi
-
-setup-generic-tool-env
 
 if [[ $DO_LIST != no ]]; then
     if [[ -z $SCBI_STORE_KEYS ]]; then
