scbi: quote all echo messages.

diff --git a/scbi b/scbi
--- a/scbi
+++ b/scbi
@@ -515,8 +515,8 @@ function handle-depends()
         if [[ $? = 0 ]]; then
             return 0
         else
-            echo No description for module $module
-            echo And not found in the distrib
+            echo "No description for module $module"
+            echo "And not found in the distrib"
             exit 1
         fi
     fi
@@ -646,7 +646,7 @@ function handle-sources()
             fi
         fi
 
-        echo -n tar-$ref > source-id
+        echo -n "tar-$ref" > source-id
 
         #  Compute and store the version id of the sources + compiler.
         #  That is when the compiler is changed when want to rebuild
@@ -695,7 +695,7 @@ function handle-sources()
                     #  compiler. That is when the compiler is changed we
                     #  want to rebuild the software.
 
-                    echo -n $ref > source-id
+                    echo -n "$ref" > source-id
 
                     vcs-build-id $SCBI_PREFIX $SCBI_TARGET $modref $(pwd)/vcs \
                                  > build-id-$variant
@@ -728,7 +728,7 @@ function handle-sources()
                     ln -s ../.vcs/$REPO vcs
                 fi
 
-                echo -n vcs-$ref > source-id
+                echo -n "vcs-$ref" > source-id
 
                 #  Compute and store the version id of the sources +
                 #  compiler. That is when the compiler is changed we
@@ -854,7 +854,7 @@ function handle-module()
     cd $SCBI_ROOT
 
     [[ ! -f $SCBI_DEFS/$module ]] &&
-        echo No description for module $module &&
+        echo "No description for module $module" &&
         exit 1
 
     #  Then load module setup
@@ -931,7 +931,7 @@ function handle-module()
     fi
 
     if [[ $DRY_RUN == yes ]]; then
-        echo $modref
+        echo "$modref"
         return 0
     fi
 
@@ -1175,7 +1175,7 @@ function handle-module()
                 return $res
             fi
 
-            [[ $step == install ]] && echo -n $variant > install-id || true
+            [[ $step == install ]] && echo -n "$variant" > install-id || true
         done
     ) || exit 1
 
@@ -1400,7 +1400,7 @@ while [[ $# -gt 0 ]]; do
             if [[ ! -d "$SCBI_DEFS" ]] || \
                    [[ -z "$(ls $SCBI_DEFS/[0-9]* 2> /dev/null)" ]];
             then
-                echo $0: no plugins found in $SCBI_DEFS
+                echo "$0: no plugins found in $SCBI_DEFS"
                 exit 1
             fi
             ;;
@@ -1432,7 +1432,7 @@ trap clean-up EXIT
     SCBI_DEFS=$HOME/.config/scbi
 
 [[ ! -d "$SCBI_DEFS" ]] &&
-    echo $0: cannot find module definition files && exit 1
+    echo "$0: cannot find module definition files" && exit 1
 
 #  Load user's environment if any now that SCBI_DEFS is set
 
@@ -1506,7 +1506,7 @@ if [[ $DO_DEPS != no ]]; then
     if [[ $? = 0 ]]; then
         {
             for MOD in "${MODULE_LIST[@]}"; do
-                echo ${MOD}
+                echo "${MOD}"
             done
         } | sort | uniq
 
