scbi: Add sub-option warning to --deps.
This sub-option will display missing external package but will not be
a fatal error.

Add corresponding regression test and documentation.

diff --git a/scbi b/scbi
--- a/scbi
+++ b/scbi
@@ -120,6 +120,7 @@ DO_VERSION=no
 DO_SHELL=no
 DO_RUN=no
 DO_RUN_CMD=
+DO_WARNING_EXTERNAL=no
 
 export SCBI_ROOT SCBI_BDIR
 export SCBI_HOST SCBI_TARGET SCBI_PLUGINS SCBI_JOBS SCBI_HALF_JOBS
@@ -331,7 +332,7 @@ function usage()
     echo "      | --clean-install    clean installation directory"
     echo "      | --tar              check for tar only if explicitly specified"
     echo "      | --tests[:only]     run the testsuite, eventually build"
-    echo "   -d | --deps             check/build dependencies"
+    echo "   -d | --deps[:warning]   check/build dependencies"
     echo "   -a | --archive          build binary archive"
     echo "      | --standalone       create a standalone source archive"
     echo "   -l | --log:n            log display control yes|no|on-failure"
@@ -669,7 +670,10 @@ function handle-depends()
             local MNAME=$fmodule
             [[ $fvariant != "default" ]] && MNAME="$MNAME/$fvariant"
 
-            echo "dependencies error building $MNAME"
+            local MSG="error"
+            [[ $DO_WARNING_EXTERNAL == yes ]] && MSG="warning"
+
+            echo "$MSG: missing dependencies for building $MNAME"
 
             for dmodule in $(get-all-depends $fmodule $fvariant build-depends); do
                 [[ ! -f $SCBI_PLUGINS/$dmodule ]] && check-pkg $dmodule
@@ -679,7 +683,13 @@ function handle-depends()
                 [[ ! -f $SCBI_PLUGINS/$dmodule ]] && check-pkg $dmodule
             done
 
-            exit 1
+            if [[ $DO_WARNING_EXTERNAL == yes ]]; then
+                false
+                return 0
+            else
+                exit 1
+            fi
+
         fi
     fi
 
@@ -1452,7 +1462,7 @@ ALLOPTS=$(getopt -u -o t:j:adefSIuscbilnpvwWh \
                  -l store,target:,no-setup,no-install,update,setup,config \
                  -l build,build-target:,install,clean-install,tar \
                  -l log,log:yes,log:no,log:on-failure,purge,purge:only \
-                 -l prefix:,tests,tests:only,help,deps \
+                 -l prefix:,tests,tests:only,help,deps,deps:warning \
                  -l archive,force,env:,no-patch,plan:,stat,stat:full \
                  -l list-depends:direct,list-depends:full,list-depends \
                  -l list-externals,list-externals:only,list-no-version \
@@ -1536,6 +1546,10 @@ while [[ $# -gt 0 ]]; do
             ;;
         -d|--deps)
             DEPS=yes
+            ;;
+        --deps:warning)
+            DEPS=yes
+            DO_WARNING_EXTERNAL=yes
             ;;
         -i|--install)
             NSTEPS="$NSTEPS install"
