New function get-vcs to get sources from a vcs.

diff --git a/scripts.d/4_scm b/scripts.d/4_scm
--- a/scripts.d/4_scm
+++ b/scripts.d/4_scm
@@ -112,3 +112,54 @@ function git-branch()
 
     return 0
 }
+
+############################## get-vcs
+
+function get-vcs()
+{
+    VCS=$1
+    URL=$2
+    module=$3
+    version=$4
+
+    local res=0
+
+    case $VCS in
+        git)
+            git-co $URL $module > $log 2>&1
+
+            if [[ ! $? = 0 ]]; then
+                echo "error: cannot get sources from $URL"
+                exit 1
+            fi
+
+            if [ "$version" != "dev" ]; then
+                git-branch $module $version
+
+                if [[ ! $? = 0 ]]; then
+                    echo "error: cannot switch to branch $version"
+                    exit 1
+                fi
+            fi
+
+            if [ "$version" = "dev" -a -d $GREPO/$module ]; then
+                ln -s $GREPO/$module local-vcs
+            fi
+
+            ;;
+        svn)
+            svn-co $URL $module > $log 2>&1
+
+            if [  "$version" = "dev" -a -d $SREPO/$module ]; then
+                ln -s $GREPO/$module local-vcs
+            fi
+
+            ;;
+        *)
+            echo "error: unknown vcs $VCS"
+            res=1
+            ;;
+    esac
+
+    return $res
+}
