Add support for option --clean-install.

diff --git a/scripts.d/5_tools b/scripts.d/5_tools
--- a/scripts.d/5_tools
+++ b/scripts.d/5_tools
@@ -1078,3 +1078,57 @@ function inherit-plugin()
         eval $H
     done
 }
+
+############################## module-clean-install
+
+function module-clean-install()
+{
+    local MPREFIX=$1
+    local MODULE=$2
+    local VARIANT=$3
+    local TARGET=$4
+    local OOT=$5
+
+    local SUDO=""
+    local _IDIR=""
+
+    fn-exists $MODULE-$VARIANT-prefix
+
+    if [[ $? = 0 ]] && [[ "$SCBI_DEFAULT_PREFIX" = "yes" ]]; then
+        _IDIR=$($MODULE-$VARIANT-prefix $MPREFIX $TARGET)
+    else
+        fn-exists $MODULE-prefix
+
+        if [[ $? = 0 ]] && [[ "$SCBI_DEFAULT_PREFIX" = "yes" ]]; then
+            _IDIR=$($MODULE-prefix $MPREFIX $TARGET $VARIANT)
+        else
+            _IDIR=$SCBI_PREFIX
+        fi
+    fi
+
+    if [[ $_IDIR != NONE ]]; then
+        if [[ ! -w ${_IDIR} ]]; then
+            SUDO=sudo
+        fi
+
+        # note that we do not want to fail here
+        # delete files in the final destination installation prefix.
+        # then delete the module install location (double check that the
+        # directory is the right one).
+
+        if [[ -f $MPREFIX/../manifest ]]; then
+            cat $MPREFIX/../manifest | while read file; do
+                $SUDO rm -f ${_IDIR}/$file
+                echo ${file%/*}
+            done | sort | uniq | while read dir; do
+                rmdir --ignore-fail-on-non-empty --parents \
+                      ${_IDIR}/$dir > /dev/null 2>&1 ;
+            done &&
+                if [[ $(basename $MPREFIX) = "install" ]] \
+                       && [[ $(basename $(dirname $MPREFIX)) = "$module" ]];
+                then
+                    cd $MPREFIX && rm -fr .
+                fi
+        fi
+    fi
+}
